#! /bin/bash
output="%Y-%m-%d-%T-screenshot.png"

case "$1" in
	"select") scrot "$output" --select --line mode=edge || exit ;;
	"window") scrot "$output" --focused --border || exit ;;
	*) scrot "$output" || exit ;;
esac
mv *"-screenshot.png" ~/pictures/screenshots/

dunstify "Screenshot taken."
